export const PERMISSIONS = {
  // Calendar
  VIEW_CALENDAR: 'VIEW_CALENDAR',
  MANAGE_CALENDAR: 'MANAGE_CALENDAR',
  
  // Appointments
  VIEW_APPOINTMENTS: 'VIEW_APPOINTMENTS',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  DELETE_APPOINTMENT: 'DELETE_APPOINTMENT',
  
  // Customers
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  
  // Staff
  VIEW_STAFF: 'VIEW_STAFF',
  MANAGE_STAFF: 'MANAGE_STAFF',
  
  // Services
  VIEW_SERVICES: 'VIEW_SERVICES',
  MANAGE_SERVICES: 'MANAGE_SERVICES',
  
  // Salon
  VIEW_SALON: 'VIEW_SALON',
  MANAGE_SALON: 'MANAGE_SALON',
  
  // Reports
  VIEW_REPORTS: 'VIEW_REPORTS',
  
  // Users (Admin only)
  MANAGE_USERS: 'MANAGE_USERS',
} as const

export type Permission = keyof typeof PERMISSIONS

export const DEFAULT_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.MANAGE_CALENDAR,
    PERMISSIONS.VIEW_APPOINTMENTS,
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.VIEW_SERVICES,
    PERMISSIONS.VIEW_SALON,
    PERMISSIONS.VIEW_REPORTS,
  ],
  STAFF: [
    PERMISSIONS.VIEW_CALENDAR,
    PERMISSIONS.VIEW_APPOINTMENTS,
  ],
  CUSTOMER: [],
}
